export const twitterUrl = 'https://x.com/Adapter_fi'
export const discordUrl = 'https://discord.gg/adapterfi'
export const telegramUrl = 'https://t.me/+HOHG2D4kXWMyNTEx'
export const githubUrl = 'https://github.com/adapter-fi'
export const docsUrl = 'https://adapter-fi.gitbook.io/adapter-finance'